"""Gelistirilmis arac özellikleri ve Sahibinden tasarimi eklendi

Revision ID: 5847e1e6a147
Revises: a4d4f17d579f
Create Date: 2026-05-20 00:42:17.472885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5847e1e6a147'
down_revision = 'a4d4f17d579f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plate', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fuel_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('transmission', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('engine_power', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('engine_power')
        batch_op.drop_column('transmission')
        batch_op.drop_column('fuel_type')
        batch_op.drop_column('plate')

    # ### end Alembic commands ###
