"""Garaj ve bildirim ozelligi eklendi

Revision ID: a4d4f17d579f
Revises: f7602d5dad7d
Create Date: 2026-05-20 00:29:09.948515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d4f17d579f'
down_revision = 'f7602d5dad7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inspection_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('maintenance_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('maintenance_date')
        batch_op.drop_column('inspection_date')

    op.drop_table('vehicle_notifications')
    # ### end Alembic commands ###
