"""Add OrderGroup and checkout fields

Revision ID: cab0f8861c23
Revises: 0f8bfb008ae9
Create Date: 2026-05-21 23:21:33.796309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cab0f8861c23'
down_revision = '0f8bfb008ae9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('price_at_purchase', sa.Float(), nullable=True))
        batch_op.create_foreign_key('fk_orders_order_group_id', 'order_groups', ['order_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_orders_order_group_id', type_='foreignkey')
        batch_op.drop_column('price_at_purchase')
        batch_op.drop_column('order_group_id')

    op.drop_table('order_groups')
    # ### end Alembic commands ###
